version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    networks:
        - clickhouse
    ulimits:
        nofile:
          soft: 262144
          hard: 262144 
    ports:
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./init/:/docker-entrypoint-initdb.d/

  
volumes:
  clickhouse-data:
networks:
    clickhouse: